# Q-Learning Algorithm

Based on this example: http://mnemstudio.org/path-finding-q-learning-tutorial.htm

1. Set gamma and matrix R
2. Initialize Q to zero
3. For each episode (training section):
    - select a random init state
    - While goal has not been reached
        - Select one among all possible actions for the current state
        - Using this possible action, consider going to the next state
        - Get maxQ for this next state based on all possible actions
        - Compute $Q(state, nextstate) = R(state, next state) + gamma*max[Q(next state, all third states)]$
    - end while
4. End for


In [210]:
import numpy as np
import random

## 1. Set gamma and matrix R

In [235]:
#                0   1   2   3   4   5
R = np.matrix([[-1, -1, -1, -1,  0,  -1],   # 0 
               [-1, -1, -1,  0, -1, 100],   # 1
               [-1, -1, -1,  0, -1,  -1],   # 2
               [-1,  0,  0, -1,  0,  -1],   # 3
               [ 0, -1, -1,  0, -1, 100],   # 4
               [-1,  0, -1, -1,  0, 100]])  # 5

gamma = 0.8

target_state = 5

## 2. Initialize Q to zero

In [236]:
Q = np.zeros((6,6))

In [237]:
Q

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

## 3. For each episode (training section - Step by step)

### 3.1. Select a random init state

In [221]:
random_init_state = np.random.randint(6)
print random_init_state
state = random_init_state

1


### 3.2. While goal has not been reached (step by step)
```
#                0   1   2   3   4   5
R = np.matrix([[-1, -1, -1, -1,  0,  -1],   # 0 
               [-1, -1, -1,  0, -1, 100],   # 1
               [-1, -1, -1,  0, -1,  -1],   # 2
               [-1,  0,  0, -1,  0,  -1],   # 3
               [ 0, -1, -1,  0, -1, 100],   # 4
               [-1,  0, -1, -1,  0, 100]])  # 5
```

#### 3.2.1. Select one among all possible actions (next state) for the current state

In [196]:
# Current state
print state

4


In [197]:
# Check all possible next states options
next_state_options = [ns for ns,r in enumerate(np.nditer(R[state])) if r>=0]
next_state_options

[0, 3, 5]

In [198]:
# Make a random choice of next state
next_state = random.choice(next_state_options)
next_state

0

#### 3.2.2. Compute $Q(state, nextstate) = R(state, next state) + gamma*max[Q(next state, all third states)]$

In [199]:
print Q[state, next_state]
print R[state, next_state]
print gamma
print Q[next_state]
print max(Q[next_state])
print Q[next_state].argmax()

0.0
0
0.8
[  0.   0.   0.   0.  80.   0.]
80.0
4


In [200]:
Q[state, next_state] = R[state, next_state] + gamma*max(Q[next_state])
print Q

[[   0.    0.    0.    0.   80.    0.]
 [   0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.]
 [  64.    0.    0.    0.    0.  100.]
 [   0.    0.    0.    0.    0.    0.]]


In [201]:
state = next_state
print state

0


#### 3.2.3. Check if goal has been reached

In [202]:
if state == target_state:
    print 'goal has been reached'
else:
    print 'goal has not been reached'
        

goal has not been reached


### 3.2. While goal has not been reached (straight forward)



In [232]:
# Print reward matrix
print 'Reward Matrix'
print R
print '\n'

# Current state
print 'Current state = {}'.format(state)
print '\n'

# Check all possible next states options
next_state_options = [ns for ns,r in enumerate(np.nditer(R[state])) if r>=0]
print 'Possible next states = {}'.format(next_state_options)
print '\n'

# Make a random choice of next state
next_state = random.choice(next_state_options)
print 'Random choice of next state = {}'.format(next_state)
print '\n'

# Compute Q[state, next_state] = R[state, next_state] + gamma*max(Q[next_state])
print 'Compute Q[state, next_state] = R[state, next_state] + gamma*max(Q[next_state])'
print 'Q[state, next_state] = {}'.format(Q[state, next_state])
print 'R[state, next_state] = {}'.format(R[state, next_state])
print 'gamma = {}'.format(gamma)
print 'Q[next_state] = {}'.format(Q[next_state])
print 'max(Q[next_state]) = {}'.format(max(Q[next_state]))
print 'Q[next_state].argmax() = {}'.format(Q[next_state].argmax())
print '\n'

Q[state, next_state] = R[state, next_state] + gamma*max(Q[next_state])
print 'Q Matrix'
print Q
print '\n'

# Set next state as new state
print 'Action: move from state {} to {}'.format(state, next_state)
state = next_state
print '\n'

# Check if goal has been reached
print 'Checking if goal has been reached:'
if state == target_state:
    print 'goal has been reached, lets start a new episode'
    random_init_state = np.random.randint(6)
    print 'new random init state = {}'.format(random_init_state)
    state = random_init_state
    print '\n'
else:
    print 'goal has not been reached'
print '\n'


Reward Matrix
[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -1  -1   0 100]]


Current state = 1


Possible next states = [3, 5]


Random choice of next state = 5


Compute Q[state, next_state] = R[state, next_state] + gamma*max(Q[next_state])
Q[state, next_state] = 0.0
R[state, next_state] = 100
gamma = 0.8
Q[next_state] = [ 0.  0.  0.  0.  0.  0.]
max(Q[next_state]) = 0.0
Q[next_state].argmax() = 0


Q Matrix
[[   0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.  100.]
 [   0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.]]


Action: move from state 1 to 5


Checking if goal has been reached:
goal has been reached, lets start a new episode
new random init state




![modeling_environment_clip_image002a.gif](http://mnemstudio.org/ai/path/images/modeling_environment_clip_image002a.gif)

## 3. For each episode (training section - Straight forward)

In [238]:
number_episodes = 20
for i in range(number_episodes):
    print '### Training section number {} ###'.format(i+1)
    random_init_state = np.random.randint(6)
    print 'new random init state = {}'.format(random_init_state)
    state = random_init_state
    print '\n'
    
    while state != target_state:
        # Print reward matrix
        print 'Reward Matrix'
        print R
        print '\n'

        # Current state
        print 'Current state = {}'.format(state)
        print '\n'

        # Check all possible next states options
        next_state_options = [ns for ns,r in enumerate(np.nditer(R[state])) if r>=0]
        print 'Possible next states = {}'.format(next_state_options)
        print '\n'

        # Make a random choice of next state
        next_state = random.choice(next_state_options)
        print 'Random choice of next state = {}'.format(next_state)
        print '\n'

        # Compute Q[state, next_state] = R[state, next_state] + gamma*max(Q[next_state])
        print 'Compute Q[state, next_state] = R[state, next_state] + gamma*max(Q[next_state])'
        print 'Q[state, next_state] = {}'.format(Q[state, next_state])
        print 'R[state, next_state] = {}'.format(R[state, next_state])
        print 'gamma = {}'.format(gamma)
        print 'Q[next_state] = {}'.format(Q[next_state])
        print 'max(Q[next_state]) = {}'.format(max(Q[next_state]))
        print 'Q[next_state].argmax() = {}'.format(Q[next_state].argmax())
        print '\n'

        Q[state, next_state] = R[state, next_state] + gamma*max(Q[next_state])
        print 'Q Matrix'
        print Q
        print '\n'

        # Set next state as new state
        print 'Action: move from state {} to {}'.format(state, next_state)
        state = next_state
        print '\n'

        # Check if goal has been reached
        print 'Checking if goal has been reached:'
        if state == target_state:
            print 'goal has been reached, lets start a new episode'
        else:
            print 'goal has not been reached'
        print '\n'

### Training section number 1 ###
new random init state = 3


Reward Matrix
[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -1  -1   0 100]]


Current state = 3


Possible next states = [1, 2, 4]


Random choice of next state = 2


Compute Q[state, next_state] = R[state, next_state] + gamma*max(Q[next_state])
Q[state, next_state] = 0.0
R[state, next_state] = 0
gamma = 0.8
Q[next_state] = [ 0.  0.  0.  0.  0.  0.]
max(Q[next_state]) = 0.0
Q[next_state].argmax() = 0


Q Matrix
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


Action: move from state 3 to 2


Checking if goal has been reached:
goal has not been reached


Reward Matrix
[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -